apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels: {{- include "rameshlabels" . | nindent 4 }}
spec:

  selector:
    matchLabels: {{- include "rameshlabels" . | nindent 6 }}
  template:
    metadata: {{- include "rameshlabels" . | nindent 6 }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.version }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.image.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          