apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels: {{- include "rameshlabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocal }}
      nodePort: {{ .Values.service.nodePort }}
  selector: {{- include "rameshlabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
